### ISSUE TITLE
Add ~1px tolerance for browser rounding

### ISSUE THREAD

**Issue by ryuran** [ryuran/sizes-webextension#2]
Sometimes there is a insignificant difference of `0.125px` or `0.250px` rounding
EDIT: sometimes it's a few more than 1px.

**Comment by nhoizey** [comment]
When using `(r)em` to define breakpoints in MQs, and image sizes, it would be nice having a higher tolerance than just `1px`.

Maybe use a 10 % tolerance, in which the color is orange instead of read?

**Comment by ryuran** [comment]
Tolerance of 1.5px added in #5. It seems cover every known cases. I hope it's enough.
